### ISSUE TITLE
Move site address to constant holding class

### ISSUE THREAD

**Issue by Egalvi** [Egalvi/GorillaGymBackend#1]
Add a module called "constants" with a class "kg.gorillagym.shop.Constants" with private constructor and private static final field holding site url "http://100pudov.kg". 
Also extract to that class following constants:
"/api/categories"
"/api/products"
"/api/submit_order"
"/api/capture"
Replace all usages of these strings to appropriate constants

**Comment by vladimir-gavrilenko** [comment]
Issue is taken to work

**Comment by Egalvi** [comment]
Deadline is December 27
